-- Human-readable reference codes for key entities.
-- NON-DESTRUCTIVE: keeps existing cuid primary keys (and all relationships)
-- intact; adds a separate, searchable `code` column generated by a Postgres
-- sequence so codes are unique, sequential and race-free on every insert
-- (including nested order-item inserts).

-- ── Sequences ────────────────────────────────────────────────────────────────
CREATE SEQUENCE IF NOT EXISTS "user_code_seq";
CREATE SEQUENCE IF NOT EXISTS "txn_code_seq";
CREATE SEQUENCE IF NOT EXISTS "order_code_seq";
CREATE SEQUENCE IF NOT EXISTS "order_item_code_seq";
CREATE SEQUENCE IF NOT EXISTS "fixed_cost_item_code_seq";
CREATE SEQUENCE IF NOT EXISTS "supplier_code_seq";

-- ── Columns + sequence-backed defaults ───────────────────────────────────────
ALTER TABLE "users" ADD COLUMN "code" TEXT;
ALTER TABLE "users" ALTER COLUMN "code" SET DEFAULT 'USR-' || lpad(nextval('user_code_seq')::text, 4, '0');

ALTER TABLE "transactions" ADD COLUMN "code" TEXT;
ALTER TABLE "transactions" ALTER COLUMN "code" SET DEFAULT 'TXN-' || lpad(nextval('txn_code_seq')::text, 6, '0');

ALTER TABLE "orders" ADD COLUMN "code" TEXT;
ALTER TABLE "orders" ALTER COLUMN "code" SET DEFAULT 'ORD-' || lpad(nextval('order_code_seq')::text, 6, '0');

ALTER TABLE "order_items" ADD COLUMN "code" TEXT;
ALTER TABLE "order_items" ALTER COLUMN "code" SET DEFAULT 'OIT-' || lpad(nextval('order_item_code_seq')::text, 6, '0');

ALTER TABLE "fixed_cost_items" ADD COLUMN "code" TEXT;
ALTER TABLE "fixed_cost_items" ALTER COLUMN "code" SET DEFAULT 'FCI-' || lpad(nextval('fixed_cost_item_code_seq')::text, 4, '0');

ALTER TABLE "suppliers" ADD COLUMN "code" TEXT;
ALTER TABLE "suppliers" ALTER COLUMN "code" SET DEFAULT 'SUP-' || lpad(nextval('supplier_code_seq')::text, 4, '0');

-- ── Backfill existing rows in creation order, then advance sequences ──────────
WITH ordered AS (
  SELECT "id", row_number() OVER (ORDER BY "createdAt", "id") AS rn FROM "users"
)
UPDATE "users" u SET "code" = 'USR-' || lpad(o.rn::text, 4, '0') FROM ordered o WHERE u."id" = o."id";
SELECT setval('user_code_seq', GREATEST((SELECT count(*) FROM "users"), 1));

WITH ordered AS (
  SELECT "id", row_number() OVER (ORDER BY "createdAt", "id") AS rn FROM "transactions"
)
UPDATE "transactions" t SET "code" = 'TXN-' || lpad(o.rn::text, 6, '0') FROM ordered o WHERE t."id" = o."id";
SELECT setval('txn_code_seq', GREATEST((SELECT count(*) FROM "transactions"), 1));

WITH ordered AS (
  SELECT "id", row_number() OVER (ORDER BY "createdAt", "id") AS rn FROM "orders"
)
UPDATE "orders" o2 SET "code" = 'ORD-' || lpad(o.rn::text, 6, '0') FROM ordered o WHERE o2."id" = o."id";
SELECT setval('order_code_seq', GREATEST((SELECT count(*) FROM "orders"), 1));

WITH ordered AS (
  SELECT "id", row_number() OVER (ORDER BY "orderId", "id") AS rn FROM "order_items"
)
UPDATE "order_items" oi SET "code" = 'OIT-' || lpad(o.rn::text, 6, '0') FROM ordered o WHERE oi."id" = o."id";
SELECT setval('order_item_code_seq', GREATEST((SELECT count(*) FROM "order_items"), 1));

WITH ordered AS (
  SELECT "id", row_number() OVER (ORDER BY "createdAt", "id") AS rn FROM "fixed_cost_items"
)
UPDATE "fixed_cost_items" f SET "code" = 'FCI-' || lpad(o.rn::text, 4, '0') FROM ordered o WHERE f."id" = o."id";
SELECT setval('fixed_cost_item_code_seq', GREATEST((SELECT count(*) FROM "fixed_cost_items"), 1));

WITH ordered AS (
  SELECT "id", row_number() OVER (ORDER BY "createdAt", "id") AS rn FROM "suppliers"
)
UPDATE "suppliers" s SET "code" = 'SUP-' || lpad(o.rn::text, 4, '0') FROM ordered o WHERE s."id" = o."id";
SELECT setval('supplier_code_seq', GREATEST((SELECT count(*) FROM "suppliers"), 1));

-- ── Unique indexes for the new codes ─────────────────────────────────────────
CREATE UNIQUE INDEX "users_code_key" ON "users"("code");
CREATE UNIQUE INDEX "transactions_code_key" ON "transactions"("code");
CREATE UNIQUE INDEX "orders_code_key" ON "orders"("code");
CREATE UNIQUE INDEX "order_items_code_key" ON "order_items"("code");
CREATE UNIQUE INDEX "fixed_cost_items_code_key" ON "fixed_cost_items"("code");
CREATE UNIQUE INDEX "suppliers_code_key" ON "suppliers"("code");

-- ── Performance index: sales listing / stats filter by type + status + date ──
CREATE INDEX "transactions_type_receiptStatus_date_idx" ON "transactions"("type", "receiptStatus", "date");
